spring:
  datasource:
    url: jdbc:h2:mem:mydb
    # Optionally use a file-based DB to persist between restarts
    # url: jdbc:h2:file:/Users/username/test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect